[project]
name = "lcdviz"
version = "0.1.0"
description = "A library for controlling 20x4 Character LCDs that actually treats them like screens"
readme = "README.md"
authors = [{ name = "NitroGuy10" }]
requires-python = ">=3.13"
dependencies = [
    "gpiozero>=2.0.1.post3",
    "rpi-gpio>=0.7.1 ; sys_platform == 'linux'",
    "smbus2>=0.6.1",
    "websockets>=17.1",
]

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pytest>=9.1.1", "ruff>=0.16.9"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-select = ["E501", "I"]
